In [1]:
import numpy as np

In [2]:
sales = np.array([120,100,15,190,170])

In [3]:
sales.sum()

np.int64(595)

In [5]:
sales.min()

np.int64(15)

In [ ]:
store = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
store.sum(axis=1)

array([ 6, 15, 24])

In [9]:
without_outlier = np.array([1,2,3,4,5])
with_outlier = np.array([1,2,3,4,10])


In [ ]:
# it help to work with the outlier
np.median(with_outlier)

np.float64(3.0)

In [12]:
np.mean(without_outlier)

np.float64(3.0)

In [14]:
# unique and square root
arr = np.array([1,1,1,2,2,2,3])
print(np.unique(arr))
print(np.sqrt(arr))

[1 2 3]
[1.         1.         1.         1.41421356 1.41421356 1.41421356
 1.73205081]


In [16]:
# position (index) of the highest and lowest sale
sales = np.array([120,100,15,190,170])

print(sales.argmax(),sales.argmin())


3 2


In [17]:
# cumulative sum -> sum of all values up to that point
sales.cumsum()

array([120, 220, 235, 425, 595])

In [18]:
sales = np.array([-120,-100,15,190,-170])
np.abs(sales)


array([120, 100,  15, 190, 170])