In [1]:
import numpy as np

In [2]:
arr_a = np.array([10,20,30,40,50])
arr_b = np.array([5,10,15,20,25])

In [4]:
arr_a+5

array([15, 25, 35, 45, 55])

In [5]:
arr_b/2

array([ 2.5,  5. ,  7.5, 10. , 12.5])

In [6]:
arr_a+arr_b

array([15, 30, 45, 60, 75])