In [1]:
import numpy as np
# Original 3x3 array
test_array = np.array([[1, 2, 3], 
                       [1, 2, 3], 
                       [1, 2, 3]])
test_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [2]:
# Scalar: 1 is added to every element
test_array + 1


array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [3]:
# Row vector (3,): stretched down the rows
test_array + np.array([3, 2, 1])

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [4]:
# Column vector (3, 1): stretched across the columns
test_array + np.array([[3], 
                       [2], 
                       [1]])

array([[4, 5, 6],
       [3, 4, 5],
       [2, 3, 4]])

In [5]:
# Shapes don't match: (3, 3) and (2,) -> ValueError
test_array + np.array([2, 1])

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [6]:
# ==============================
# PRACTICE QUESTIONS
# ==============================

In [7]:
# Q1. GST: add 18% tax to every price in this 2 x 3 price table
prices = np.array([[100, 250, 400],
                   [150, 300, 500]])
prices+(prices*.18)

array([[118., 295., 472.],
       [177., 354., 590.]])

In [9]:
# Q2. Grace marks per SUBJECT: 3 students x 4 subjects
#     Add [2, 0, 5, 3] so each subject gets its own grace marks
marks = np.array([[45, 60, 38, 70],
                  [55, 48, 62, 40],
                  [30, 75, 50, 66]])
marks + np.array([2,0,5,3])

array([[47, 60, 43, 73],
       [57, 48, 67, 43],
       [32, 75, 55, 69]])

In [10]:
# Q3. Bonus per STUDENT: add 5, 0 and 10 marks to the 3 students (same marks array)
#     Hint: the bonus must be a column
marks = np.array([[45, 60, 38, 70],
                  [55, 48, 62, 40],
                  [30, 75, 50, 66]])
# Your code here
marks + np.array([[5],
                  [0],
                  [10]])

array([[50, 65, 43, 75],
       [55, 48, 62, 40],
       [40, 85, 60, 76]])

In [ ]:
# Q5. (Challenge) Make a multiplication table from 1 to 10 without any loop
#     Hint: multiply a row vector by a column vector
# Your code here
np.arange(1,11) * np.arange(1,11).reshape(10,1)
# Your code here

ValueError: cannot reshape array of size 10 into shape (10,2)