In [1]:
import numpy as np 

In [2]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [3]:
np.arange(1,11,1)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.linspace(0,1000,10)

array([   0.        ,  111.11111111,  222.22222222,  333.33333333,
        444.44444444,  555.55555556,  666.66666667,  777.77777778,
        888.88888889, 1000.        ])

In [13]:
# 3 by 4 ki matrix

temp_array = np.array([[5,6,9,4],
                       [1,2,3,1],
                       [4,5,6,1],
                       ]
                      )
temp_array


array([[5, 6, 9, 4],
       [1, 2, 3, 1],
       [4, 5, 6, 1]])

In [14]:
temp_array = temp_array.reshape(4, 3)
temp_array

array([[5, 6, 9],
       [4, 1, 2],
       [3, 1, 4],
       [5, 6, 1]])