In [1]:
import numpy as np
# 1. Convert grades: "Pass" if score >= 50, else "Fail"
scores = np.array([45, 67, 32, 90, 58])
result = np.where(scores >= 50, "Pass", "Fail")
result

array(['Fail', 'Pass', 'Fail', 'Pass', 'Pass'], dtype='<U4')

In [2]:
# 2. Make numbers positive: replace negatives with 0
nums = np.array([-4, -1, 3, -7, 8, 0])
positive_nums = np.where(nums < 0, 0, nums)
positive_nums

array([0, 0, 3, 0, 8, 0])

In [3]:
# 3. Apply discount: 10% off if price > 100
prices = np.array([80, 120, 150, 90, 200])
final_prices = np.where(prices > 100, prices * 0.9, prices)
final_prices

array([ 80., 108., 135.,  90., 180.])

In [4]:
# 4. Categorize ages: "Child" if under 18, else "Adult"
ages = np.array([8, 15, 22, 35, 60, 70])
category = np.where(ages < 18, "Child", "Adult")
category

array(['Child', 'Child', 'Adult', 'Adult', 'Adult', 'Adult'], dtype='<U5')

In [5]:
# 5. Label numbers: "Even" if divisible by 2, else "Odd"
nums = np.array([1, 2, 3, 4, 5, 6])
labels = np.where(nums % 2 == 0, "Even", "Odd")
labels

array(['Odd', 'Even', 'Odd', 'Even', 'Odd', 'Even'], dtype='<U4')

In [6]:
# 6. Cap values at a maximum of 100 (upper bound)
values = np.array([10, 25, 50, 75, 120])
capped = np.where(values > 100, 100, values)
capped

array([ 10,  25,  50,  75, 100])